"""add wallets table

Revision ID: 194ee4039e87
Revises: e37c9c2cef55
Create Date: 2026-03-04 09:27:53.383899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194ee4039e87'
down_revision = 'e37c9c2cef55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
